### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by WREQI** [rodydavis/FlutterWebXRThreeJS#1]
How to run locally

**Comment by KonstantinKolesnik** [comment]
Hi Rody. The source code doesn't build. A lot of errors like "JS interop classes do not support non-external constructors. Try annotating with `external`."
What could be wrong?

**Comment by AkhilRaja** [comment]
+1 @rodydavis Any steps how to run this locally ?

**Comment by rodydavis** [comment]
You probably need to regenerate the bindings, also it was made with an older version of dart as well
